### ISSUE TITLE
Slack invite link only allows emails from certain domains?

### ISSUE THREAD

**Issue by shawaj** [magma/community#13]
Not sure if this is intentional, but the slack invite link in the readme: https://join.slack.com/t/magmacore/shared_invite/zt-g76zkofr-g6~jYiS3KRzC9qhAISUC2A

Only allows you to sign up if you have an email address at a certain domain name:

![image](https://user-images.githubusercontent.com/3359418/132787225-58beca17-772a-40f8-b44d-0a92021e7027.png)

**Comment by kuohsianglu** [comment]
How to join the magma slack community without the certain domain?

**Comment by shawaj** [comment]
@kuohsianglu no idea! Nobody ever replied

**Comment by ttx** [comment]
You should be able to join at the following URL: https://slack.magmacore.org/
Let me know if it works and I'll update the README here.

**Comment by shawaj** [comment]
Thanks @ttx that's worked great

**Comment by lucasgonze** [comment]
Closing as part of archiving the repo.
