### ISSUE TITLE
doubts about Magma Feature

### ISSUE THREAD

**Issue by 07350100647** [magma/community#17]
Hello, i am doing a search about Open Source Core (EPC), and is not clear for me in the documentation the answers for the follow questions. If some one can help me, i will be grateful.

The MME can handling of UE procedures: Security configuration, tracking area update, service access and radio bearer establishment?

Is possible to configure IP range, DNS and E-RAB QoS?

The release v1.6.1 has support to voice over LTE (VoLTE)?

 Has Support of broadcast and multicast PDN options?

The release v1.6.1 has support to IPV6?

Supposing the throughput of 40Mbs by one eNodeB (BW=5MHz, MIMO 2X2). How many eNodeBs the Magma can support? Wich is the throughput maximum that the Magma can support?

Thank you very much!

**Comment by platonenkoiurii** [comment]
hi

try to ask on Magma Slack
https://magmacore.slack.com/
